---
    - name: 'Update repository and system by running:'
      apt: 
        update_cache: yes  
        upgrade: dist  
       
    - name: 'Set time zone to Yekaterinburg'
      timezone:
        name: Asia/Yekaterinburg

    - name: 'generate locale ru_RU.UTF-8'
      locale_gen:
        name: ru_RU.UTF-8
        state: present
      

    - name: 'Install Recomended packages:'
      apt: name={{ item }} state=present update_cache=yes 
      with_items:
        - htop
        - iotop
        - mc
        - tmux
        - strace
        - python-pip
        - apt-transport-https
        - ca-certificates 
        - curl 
        - gnupg2 
        - software-properties-common
        - dirmngr
        - python-apt
        - git-core
        - ntpdate
        - ntp
      register: recomendedinstalled

    - name: 'Copy ntp config'
      when: recomendedinstalled|success
      copy: src=ntp.conf dest={{ ntp_config_path }}  owner=root group=root  
      backup: yes
   
    - name: Update time
      command: ntpdate -q '{{ ntp_server }}'

    - name: 'Add an Apt signing key, for docker'
      apt_key:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg 
        state: present

    - name: 'Add apt repository for docker'
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable
        state: present
        filename: 'docker-ce'
        update_cache: yes

    
    - name: 'Install docker packages'
      apt: name={{ item }} state=present update_cache=yes 
      with_items:
        - docker-ce
        - docker-compose
        
    

    - name: 'Upgrade pip'
      pip:
        name: pip
        extra_args: --upgrade
      tags: pip 

    - name: 'Install py-docker'
      pip:
        name: docker
        state: present
      tags: pip  
    



   

  
