---
    - name: 'Update repository and system by running:'
      apt: 
        update_cache: yes  
        upgrade: dist  
       
    - name: 'Set time zone to Yekaterinburg'
      timezone:
        name: Asia/Yekaterinburg

    - name: 'generate locale ru_RU.UTF-8'
      locale_gen:
        name: ru_RU.UTF-8
        state: present
      

    - name: 'Install Recomended packages:'
      apt: name={{ item }} state=present update_cache=yes 
      with_items:
        - krb5-user
        - samba samba-common-bin
        - winbind
        - ntp
        - ntpdate
        - libpam-krb5
        - libpam-winbind
        - libnss-winbind
        - libpam-ccreds
        - nscd
        - nss-updatedb
        - libnss-db
        - htop
        - iotop
        - mc
        - tmux
        - strace
        - python-pip
        - apt-transport-https
        - ca-certificates 
        - curl 
        - gnupg2 
        - software-properties-common
        - dirmngr
        - python-apt
        - git-core
        
        
      register: recomendedinstalled

    
    - name: 'Copy ntp config'
      when: recomendedinstalled
      template:
         src: ntp.conf.j2
         dest: {{ config_path }}
         backup: yes   
     
    - name: 'Copy common-session'
      when: recomendedinstalled
      template:
         src: common-session.j2
         dest: {{ config_path }}/pam.d
         backup: yes   
    
    - name: 'Copy krb5 config'
      when: recomendedinstalled
      template:
         src: krb5.conf.j2
         dest: {{ config_path }}
         backup: yes   
    
    - name: 'Copy limits config'
      when: recomendedinstalled
      template:
         src: limits.conf.j2
         dest: {{ config_path }}/security/
         backup: yes   
   
    - name: 'Copy nsswitch config'
      when: recomendedinstalled
      template:
         src: nsswitch.conf.j2
         dest: {{ config_path }}
         backup: yes   
   
    - name: 'Copy smb config'
      when: recomendedinstalled
      template:
         src: smb.conf.j2
         dest: {{ config_path }}/samba/
         backup: yes
       notify:
       - ntp restart
       - winbind stop
       - smb restart
       - winbind restart
   
    - name: Update time
      command: ntpdate -q '{{ ntp_server }}'

    - name: Join to domain
      command: net ads join -U '{{ domain_user }}'%'{{ domain_user_password }}' -D '{{ domain_name }}'